spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
  config:
    import: configserver:http://127.0.0.1:8888
  application:
    name: order
  datasource:
    password: '123456'
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/etiya
  cloud:
    loadbalancer:
      retry:
        retry-on-all-operations: true
        max-retries-on-same-service-instance: 0
        max-retries-on-next-service-instance: 3
server:
  error:
    include-stacktrace: never
    include-exception: 'true'
    include-binding-errors: always
    include-message: always
  port: ${PORT:10000}
resilience4j:
  retry:
    instances:
      restaurant_retry:
        max-attempts: 2
        wait-duration: '1ms'
  circuitbreaker:
    instances:
      restaurant_cb:
        sliding-window-type: count-based
        sliding-window-size: 20
        minimum-number-of-calls: 10
        failure-rate-threshold: 30
        wait-duration-in-open-state: '2s'
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 10
        max-wait-duration-in-half-open-state: '10s'
        slow-call-duration-threshold: 500
        slow-call-rate-threshold: 90
